package crawler

import "github.com/twitocode/sift/internal/common"

var seeds = []common.URL{
	// Reference / Knowledge
	"https://www.britannica.com/",
	"https://plato.stanford.edu/",
	"https://www.gutenberg.org/ebooks/",
	"https://archive.org/",
	"https://www.loc.gov/",
	"https://www.smithsonianmag.com/",
	"https://www.si.edu/",
	"https://www.nationalgeographic.com/",
	"https://www.history.com/",
	"https://www.science.org/",
  "https://www.wikipedia.org",

	// Programming / Technology
	"https://stackoverflow.com/questions",
	"https://stackexchange.com/sites",
	"https://developer.mozilla.org/en-US/docs/Web",
	"https://docs.python.org/3/",
	"https://go.dev/doc/",
	"https://doc.rust-lang.org/book/",
	"https://dev.java/learn/",
	"https://learn.microsoft.com/en-us/docs/",
	"https://developer.apple.com/documentation/",
	"https://www.gnu.org/manual/manual.html",
	"https://www.w3.org/TR/",
	"https://www.ietf.org/standards/",
	"https://www.kernel.org/doc/html/latest/",
	"https://npmjs.com/",
	"https://pypi.org/",
	"https://crates.io/",
	"https://arxiv.org/",
	"https://www.usenix.org/publications",

	// Software / Open Source
	"https://github.com/explore",
	"https://github.com/topics",
	"https://gitlab.com/explore",
	"https://sourceforge.net/directory/",
	"https://codeberg.org/explore/repos",
	"https://www.apache.org/",
	"https://www.mozilla.org/en-US/firefox/",
	"https://opensource.org/licenses/",
	"https://www.linuxfoundation.org/projects",

	// News
	"https://www.bbc.com/news",
	"https://www.reuters.com/",
	"https://apnews.com/",
	"https://www.theguardian.com/international",
	"https://www.npr.org/sections/news/",
	"https://www.cbc.ca/news",
	"https://www.pbs.org/newshour/",
	"https://www.aljazeera.com/",
	"https://www.dw.com/en/top-stories/s-9097",
	"https://www.france24.com/en/",
	"https://www.nbcnews.com/",
	"https://www.washingtonpost.com/",
	"https://www.wsj.com/",
	"https://www.theatlantic.com/",
	"https://time.com/",

	// Science / Academia
	"https://www.nature.com/",
	"https://www.sciencedirect.com/",
	"https://www.pnas.org/",
	"https://www.cell.com/",
	"https://journals.plos.org/",
	"https://academic.oup.com/journals/",
	"https://www.cambridge.org/core/",
	"https://www.jstor.org/",
	"https://eric.ed.gov/",
	"https://www.ncbi.nlm.nih.gov/",
	"https://pubmed.ncbi.nlm.nih.gov/",
	"https://www.cdc.gov/",
	"https://www.who.int/",
	"https://www.nasa.gov/",
	"https://www.noaa.gov/",

	// Universities / Research
	"https://www.mit.edu/",
	"https://www.stanford.edu/",
	"https://www.harvard.edu/",
	"https://www.berkeley.edu/",
	"https://www.cmu.edu/",
	"https://www.princeton.edu/",
	"https://www.yale.edu/",
	"https://www.cornell.edu/",
	"https://www.ucla.edu/",
	"https://www.utoronto.ca/",
	"https://www.ubc.ca/",
	"https://www.mcgill.ca/",
	"https://www.mcmaster.ca/",
	"https://uwaterloo.ca/",

	// Government / Public Data
	"https://www.usa.gov/",
	"https://www.data.gov/",
	"https://www.census.gov/",
	"https://www.congress.gov/",
	"https://www.loc.gov/",
	"https://www.canada.ca/",
	"https://www.statcan.gc.ca/",
	"https://www.ontario.ca/",
	"https://open.canada.ca/",
	"https://www.nrcan.gc.ca/",
	"https://www.govinfo.gov/",
	"https://www.europarl.europa.eu/",
	"https://data.europa.eu/",

	// Books / Movies / Culture
	"https://www.imdb.com/chart/",
	"https://www.goodreads.com/list",
	"https://www.goodreads.com/book",
	"https://www.themoviedb.org/",
	"https://letterboxd.com/films/",
	"https://www.rottentomatoes.com/",
	"https://www.metacritic.com/",
	"https://www.poetryfoundation.org/",
	"https://www.poetryarchive.org/",
	"https://www.moma.org/",
	"https://www.metmuseum.org/art/collection",

	// Communities / Discussion
	"https://news.ycombinator.com/",
	"https://lobste.rs/",
	"https://slashdot.org/",
	"https://www.lesswrong.com/",
	"https://forum.manjaro.org/",
	"https://forums.swift.org/",
	"https://discuss.python.org/",
	"https://community.grafana.com/",
	"https://discourse.ubuntu.com/",
	"https://forums.tomshardware.com/",

	// Travel / Geography
	"https://www.lonelyplanet.com/",
	"https://www.wikivoyage.org/",
	"https://www.nps.gov/",
	"https://www.nationalparks.org/",
	"https://earthobservatory.nasa.gov/",
	"https://www.openstreetmap.org/",
	"https://www.geonames.org/",

	// Business / Economics / Finance
	"https://www.sec.gov/",
	"https://www.federalreserve.gov/",
	"https://www.bls.gov/",
	"https://www.bea.gov/",
	"https://www.oecd.org/",
	"https://www.imf.org/",
	"https://www.worldbank.org/",
	"https://www.bis.org/",
	"https://www.bankofcanada.ca/",

	// GitHub Awesome Lists & Meta-Hubs
	"https://github.com/sindresorhus/awesome",
	"https://awesome.re",
	"https://github.com/emijrp/awesome-awesome",
	"https://github.com/bayandin/awesome-awesomeness",
	"https://github.com/trackawesomelist/trackawesomelist",
	"https://github.com/vinta/awesome-python",
	"https://github.com/avelino/awesome-go",
	"https://github.com/sorrycc/awesome-javascript",
	"https://github.com/sindresorhus/awesome-nodejs",
	"https://github.com/rust-unofficial/awesome-rust",
	"https://github.com/enaqx/awesome-react",
	"https://github.com/vuejs/awesome-vue",
	"https://github.com/isocpp/awesome-cpp",
	"https://github.com/josephmisiti/awesome-machine-learning",
	"https://github.com/Hannibal046/Awesome-LLM",
	"https://github.com/ChristosChristofidis/awesome-deep-learning",
	"https://github.com/awesome-selfhosted/awesome-selfhosted",
	"https://github.com/ripienaar/free-for-dev",
	"https://github.com/public-apis/public-apis",
	"https://github.com/trimstray/the-book-of-secret-knowledge",
	"https://github.com/Lissy93/awesome-privacy",
	"https://github.com/kamranahmedse/developer-roadmap",
	"https://github.com/EbookFoundation/free-programming-books",
	"https://github.com/jwasham/coding-interview-university",
	"https://github.com/papers-we-love/papers-we-love",
	"https://github.com/awesomedata/awesome-public-datasets",
	"https://github.com/kahun/awesome-sysadmin",
	"https://github.com/rothgar/awesome-tuis",

	// Reddit (old.reddit.com Subreddits)
	"https://old.reddit.com/r/InternetIsBeautiful/",
	"https://old.reddit.com/r/opendirectories/",
	"https://old.reddit.com/r/selfhosted/",
	"https://old.reddit.com/r/programming/",
	"https://old.reddit.com/r/datasets/",
	"https://old.reddit.com/r/DataHoarder/",
	"https://old.reddit.com/r/webdev/",
	"https://old.reddit.com/r/UsefulWebsites/",
	"https://old.reddit.com/r/coolgithubprojects/",
	"https://old.reddit.com/r/open_source/",

	// Web Directories, Small Web & IndieWeb Catalogs
	"https://curlie.org",
	"https://theindex.fyi",
	"https://ooh.directory",
	"https://blogroll.org",
	"https://blogscroll.github.io",
	"https://gossipsweb.net",
	"https://indieseek.xyz",
	"https://wiby.me",
	"https://search.marginalia.nu/explore",
	"https://neocities.org/browse",
	"https://512kb.club",
	"https://1mb.club",
	"https://darktheme.club",
	"https://url.town",
	"https://devpages.io",
	"https://free-for.dev",
	"https://vlib.org",
	"https://directory.fsf.org/wiki/Main_Page",

	// Link Aggregators, Product Catalogs & Software Discovery
	"https://alternativeto.net",
	"https://www.saashub.com",
	"https://readsomethingwonderful.com",
	"https://www.producthunt.com",
	"https://alltop.com",
	"https://www.techmeme.com",
	"https://techurls.com",
	"https://upstract.com",
	"https://brutalist.report",
	"https://daily.dev",
	"https://tildes.net",
	"https://www.opensourcealternative.to",
	"https://www.libhunt.com",
	"https://catalog.data.gov/dataset",
	"https://openalex.org",
	"https://doaj.org",

	// Health, Medicine & Biomedical Research
	"https://pubmed.ncbi.nlm.nih.gov/",
	"https://www.ncbi.nlm.nih.gov/pmc/",
	"https://www.ncbi.nlm.nih.gov/books/",
	"https://europepmc.org/",
	"https://clinicaltrials.gov/",
	"https://www.cochranelibrary.com/cdsr/reviews/topics",
	"https://www.tripdatabase.com/",
	"https://openmd.com/directory",
	"https://openmd.com/",
	"https://medlineplus.gov/healthtopics.html",
	"https://medlineplus.gov/encyclopedia.html",
	"https://medlineplus.gov/druginformation.html",
	"https://medlineplus.gov/genetics/",
	"https://www.nih.gov/health-information",
	"https://www.cdc.gov/health-topics/index.html",
	"https://www.who.int/health-topics",
	"https://www.who.int/data/gho",
	"https://www.nhs.uk/conditions/",
	"https://www.nice.org.uk/guidance",
	"https://www.merckmanuals.com/professional",
	"https://www.merckmanuals.com/home",
	"https://www.uptodate.com/contents/table-of-contents",
	"https://www.mayoclinic.org/diseases-conditions",
	"https://www.mayoclinic.org/tests-procedures",
	"https://www.mayoclinic.org/drugs-supplements",
	"https://my.clevelandclinic.org/health",
	"https://www.hopkinsmedicine.org/health/conditions-and-diseases",
	"https://www.health.harvard.edu/",
	"https://www.cancer.gov/",
	"https://www.orpha.net/",
	"https://rarediseases.info.nih.gov/",
	"https://rarediseases.org/rare-diseases/",
	"https://www.biomedcentral.com/journals",
	"https://www.bmj.com/",
	"https://jamanetwork.com/",
	"https://www.thelancet.com/",
	"https://www.nejm.org/",
	"https://journals.plos.org/plosmedicine/",
	"https://www.medrxiv.org/",
	"https://www.biorxiv.org/",
	"https://dailymed.nlm.nih.gov/dailymed/",
	"https://www.drugs.com/",
	"https://www.rxlist.com/",
	"https://pubchem.ncbi.nlm.nih.gov/",
	"https://www.fda.gov/drugs",
	"https://www.ema.europa.eu/en/medicines",
	"https://www.healthdata.org/",
	"https://ourworldindata.org/health-meta",
	"https://www.webmd.com/a-to-z-guides/common-topics",
	"https://www.healthline.com/directory/topics",
	"https://www.medicalnewstoday.com/",
}


