// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: index.sql

package db

import (
	"context"
)

const addDocumentMeta = `-- name: AddDocumentMeta :exec
INSERT INTO
  documents (token_count, page_id)
VALUES
  (?, ?)
`

type AddDocumentMetaParams struct {
	TokenCount int64
	PageID     int64
}

func (q *Queries) AddDocumentMeta(ctx context.Context, arg AddDocumentMetaParams) error {
	_, err := q.db.ExecContext(ctx, addDocumentMeta, arg.TokenCount, arg.PageID)
	return err
}

const addIndexMeta = `-- name: AddIndexMeta :exec
INSERT INTO
  index_metadata (
    document_count,
    total_token_count,
    average_doc_length
  )
VALUES
  (?, ?, ?)
`

type AddIndexMetaParams struct {
	DocumentCount    int64
	TotalTokenCount  int64
	AverageDocLength int64
}

func (q *Queries) AddIndexMeta(ctx context.Context, arg AddIndexMetaParams) error {
	_, err := q.db.ExecContext(ctx, addIndexMeta, arg.DocumentCount, arg.TotalTokenCount, arg.AverageDocLength)
	return err
}

const deleteAllDocuments = `-- name: DeleteAllDocuments :exec
DELETE FROM documents
`

func (q *Queries) DeleteAllDocuments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDocuments)
	return err
}

const deleteAllIndexMeta = `-- name: DeleteAllIndexMeta :exec
DELETE FROM index_metadata
`

func (q *Queries) DeleteAllIndexMeta(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIndexMeta)
	return err
}

const getAllDocumentMeta = `-- name: GetAllDocumentMeta :many
SELECT
  id, token_count, page_id
FROM
  documents
`

func (q *Queries) GetAllDocumentMeta(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getAllDocumentMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(&i.ID, &i.TokenCount, &i.PageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentMeta = `-- name: GetDocumentMeta :one
SELECT
  id, token_count, page_id
FROM
  documents
WHERE
  id = ?
`

func (q *Queries) GetDocumentMeta(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentMeta, id)
	var i Document
	err := row.Scan(&i.ID, &i.TokenCount, &i.PageID)
	return i, err
}

const getLatestIndexMeta = `-- name: GetLatestIndexMeta :one
SELECT
  document_count, total_token_count, average_doc_length
FROM
  index_metadata
ORDER BY
  id DESC
LIMIT
  1
`

type GetLatestIndexMetaRow struct {
	DocumentCount    int64
	TotalTokenCount  int64
	AverageDocLength int64
}

func (q *Queries) GetLatestIndexMeta(ctx context.Context) (GetLatestIndexMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestIndexMeta)
	var i GetLatestIndexMetaRow
	err := row.Scan(&i.DocumentCount, &i.TotalTokenCount, &i.AverageDocLength)
	return i, err
}
