// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Document struct {
	ID         int64
	TokenCount int64
	PageID     int64
}

type IndexMetadatum struct {
	DocumentCount    int64
	TotalTokenCount  int64
	AverageDocLength int64
}

type Link struct {
	FromUrl sql.NullString
	ToUrl   sql.NullString
}

type Page struct {
	ID                int64
	RequestUrl        string
	Title             sql.NullString
	Description       sql.NullString
	Text              sql.NullString
	StatusCode        sql.NullInt64
	CrawledAt         sql.NullTime
	ContentHash       sql.NullInt64
	HasBeenCrawled    sql.NullInt64
	DuplicateOf       sql.NullInt64
	FoundCanonical    sql.NullString
	FinalUrl          string
	ResolvedCanonical sql.NullInt64
}
