// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const assignCanonical = `-- name: AssignCanonical :exec
UPDATE pages
SET
  duplicate_of = ?
WHERE
  id = ?
LIMIT
  1
`

type AssignCanonicalParams struct {
	DuplicateOf sql.NullInt64
	ID          int64
}

func (q *Queries) AssignCanonical(ctx context.Context, arg AssignCanonicalParams) error {
	_, err := q.db.ExecContext(ctx, assignCanonical, arg.DuplicateOf, arg.ID)
	return err
}

const batchAssignCanonical = `-- name: BatchAssignCanonical :exec
UPDATE pages
SET
  duplicate_of = ?
WHERE
  id IN (/*SLICE:ids*/?)
`

type BatchAssignCanonicalParams struct {
	DuplicateOf sql.NullInt64
	Ids         []int64
}

func (q *Queries) BatchAssignCanonical(ctx context.Context, arg BatchAssignCanonicalParams) error {
	query := batchAssignCanonical
	var queryParams []interface{}
	queryParams = append(queryParams, arg.DuplicateOf)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteAll = `-- name: DeleteAll :exec
DELETE FROM pages
`

func (q *Queries) DeleteAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAll)
	return err
}

const findPageByID = `-- name: FindPageByID :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      pages
    WHERE
      id = ?
  )
`

func (q *Queries) FindPageByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPageByID, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findPageByURL = `-- name: FindPageByURL :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      pages
    WHERE
      url = ?
  )
`

func (q *Queries) FindPageByURL(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPageByURL, url)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllPages = `-- name: GetAllPages :many
SELECT
  id, url, title, description, text, status_code, crawled_at, content_hash, has_been_crawled, duplicate_of, found_canonical
FROM
  pages
WHERE
  has_been_crawled = TRUE
`

func (q *Queries) GetAllPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, getAllPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.StatusCode,
			&i.CrawledAt,
			&i.ContentHash,
			&i.HasBeenCrawled,
			&i.DuplicateOf,
			&i.FoundCanonical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageInfoByID = `-- name: GetPageInfoByID :one
SELECT
  id, url, title, description, text, status_code, crawled_at, content_hash, has_been_crawled, duplicate_of, found_canonical
FROM
  pages
WHERE
  id = ?
`

func (q *Queries) GetPageInfoByID(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageInfoByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.StatusCode,
		&i.CrawledAt,
		&i.ContentHash,
		&i.HasBeenCrawled,
		&i.DuplicateOf,
		&i.FoundCanonical,
	)
	return i, err
}

const getPageInfoByURL = `-- name: GetPageInfoByURL :one
SELECT
  id, url, title, description, text, status_code, crawled_at, content_hash, has_been_crawled, duplicate_of, found_canonical
FROM
  pages
WHERE
  url = ?
`

func (q *Queries) GetPageInfoByURL(ctx context.Context, url string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageInfoByURL, url)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.StatusCode,
		&i.CrawledAt,
		&i.ContentHash,
		&i.HasBeenCrawled,
		&i.DuplicateOf,
		&i.FoundCanonical,
	)
	return i, err
}

const setPageInfo = `-- name: SetPageInfo :exec
INSERT
OR REPLACE INTO pages (
  url,
  title,
  text,
  description,
  status_code,
  crawled_at,
  has_been_crawled,
  content_hash,
  found_canonical
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SetPageInfoParams struct {
	Url            string
	Title          sql.NullString
	Text           sql.NullString
	Description    sql.NullString
	StatusCode     sql.NullInt64
	CrawledAt      sql.NullTime
	HasBeenCrawled sql.NullInt64
	ContentHash    sql.NullInt64
	FoundCanonical sql.NullString
}

func (q *Queries) SetPageInfo(ctx context.Context, arg SetPageInfoParams) error {
	_, err := q.db.ExecContext(ctx, setPageInfo,
		arg.Url,
		arg.Title,
		arg.Text,
		arg.Description,
		arg.StatusCode,
		arg.CrawledAt,
		arg.HasBeenCrawled,
		arg.ContentHash,
		arg.FoundCanonical,
	)
	return err
}
