// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page.sql

package db

import (
	"context"
	"database/sql"
)

const findPage = `-- name: FindPage :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      pages
    WHERE
      url = ?
  )
`

func (q *Queries) FindPage(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPage, url)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllPages = `-- name: GetAllPages :many
SELECT url, title, description, text, status_code, crawled_at, content_hash, has_been_crawled FROM pages WHERE has_been_crawled = TRUE
`

func (q *Queries) GetAllPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, getAllPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.StatusCode,
			&i.CrawledAt,
			&i.ContentHash,
			&i.HasBeenCrawled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageInfo = `-- name: GetPageInfo :one
SELECT
  url, title, description, text, status_code, crawled_at, content_hash, has_been_crawled
FROM
  pages
WHERE
  url = ?
`

func (q *Queries) GetPageInfo(ctx context.Context, url string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageInfo, url)
	var i Page
	err := row.Scan(
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.StatusCode,
		&i.CrawledAt,
		&i.ContentHash,
		&i.HasBeenCrawled,
	)
	return i, err
}

const setPageInfo = `-- name: SetPageInfo :exec
INSERT
OR REPLACE INTO pages (
  url,
  title,
  text,
  description,
  status_code,
  crawled_at,
  has_been_crawled,
  content_hash
)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?)
`

type SetPageInfoParams struct {
	Url            string
	Title          sql.NullString
	Text           sql.NullString
	Description    sql.NullString
	StatusCode     sql.NullInt64
	CrawledAt      sql.NullTime
	HasBeenCrawled sql.NullInt64
	ContentHash    sql.NullInt64
}

func (q *Queries) SetPageInfo(ctx context.Context, arg SetPageInfoParams) error {
	_, err := q.db.ExecContext(ctx, setPageInfo,
		arg.Url,
		arg.Title,
		arg.Text,
		arg.Description,
		arg.StatusCode,
		arg.CrawledAt,
		arg.HasBeenCrawled,
		arg.ContentHash,
	)
	return err
}
