// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const get = `-- name: Get :one
SELECT 1
`

func (q *Queries) Get(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, get)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
